
DELETE FROM PAYMENTS;
DELETE FROM RIDE_TRANSACTION;
DELETE FROM CUSTOMER_ADDRESS;
DELETE FROM CUSTOMERS;



DELETE FROM RIDE_TRANSACTION;
DELETE FROM CARS_AT_PICKUP;
DELETE FROM PICKUP_POINTS;
DELETE FROM CAR;