
SELECT USER FROM DUAL;

--------------------------------------
--          ROLES
--------------------------------------
    CREATE ROLE APP_OWNER;
    CREATE ROLE DEVELOPER;
    CREATE ROLE TESTER;
    CREATE ROLE ANALYST;
    CREATE ROLE SERVICE;
    CREATE ROLE SECURITY;

---------------------------------------
---         APP_OWNER
---------------------------------------
    GRANT  CONNECT, CREATE SESSION to APP_OWNER;
    GRANT CREATE ANY TABLE TO APP_OWNER;
    GRANT ALL ON ACTIVITY to APP_OWNER;
    GRANT ALL ON CAR to APP_OWNER;
    GRANT ALL ON CARS_AT_PICKUP to APP_OWNER;
    GRANT ALL ON CUSTOMER_ADDRESS to APP_OWNER;
    GRANT ALL ON CUSTOMERS to APP_OWNER;
    GRANT ALL ON DISCOUNTS to APP_OWNER;
    GRANT ALL ON FEEDBACK to APP_OWNER;
    GRANT ALL ON INSURANCE to APP_OWNER;
    GRANT ALL ON MAINTENANCE to APP_OWNER;
    GRANT ALL ON PAYMENTS to APP_OWNER;
    GRANT ALL ON PICKUP_POINTS to APP_OWNER;
    GRANT ALL ON PURCHASE_INSURANCE to APP_OWNER;
    GRANT ALL ON RIDE_TRANSACTION to APP_OWNER;
    GRANT ALL ON SUPPORT to APP_OWNER;
    GRANT ALL ON VIOLATIONS to APP_OWNER;
    GRANT ALL ON VIOLATIONS_RECORDS to APP_OWNER;
    
    GRANT ALL ON PCKG_CAR TO APP_OWNER;
    GRANT ALL ON PCKG_CUSTOMER TO APP_OWNER;
    GRANT ALL ON PCKG_INSURANCE TO APP_OWNER;
    GRANT ALL ON PCKG_SERVICE TO APP_OWNER;
    GRANT ALL ON PCKG_TRANSACT TO APP_OWNER; 
    GRANT ALL ON PCKG_VIOLATIONS TO APP_OWNER;
    GRANT ALL ON PCKG_UTILS TO APP_OWNER;

    GRANT ALL ON ANALYST_VIEW TO APP_OWNER;
    GRANT ALL ON SUPPORT_VIEW TO APP_OWNER;
    GRANT ALL ON AUDIT_VIEW TO APP_OWNER;

---------------------------------------
---         DEVELOPER
---------------------------------------
    GRANT CONNECT, CREATE SESSION TO DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON ACTIVITY to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CAR to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CARS_AT_PICKUP to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CUSTOMER_ADDRESS to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CUSTOMERS to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON DISCOUNTS to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON FEEDBACK to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON INSURANCE to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON MAINTENANCE to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON PAYMENTS to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON PICKUP_POINTS to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON PURCHASE_INSURANCE to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON RIDE_TRANSACTION to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON SUPPORT to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON VIOLATIONS to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON VIOLATIONS_RECORDS to DEVELOPER;
    
    GRANT ALL ON PCKG_CAR TO DEVELOPER;
    GRANT ALL ON PCKG_CUSTOMER TO DEVELOPER;
    GRANT ALL ON PCKG_INSURANCE TO DEVELOPER;
    GRANT ALL ON PCKG_SERVICE TO DEVELOPER;
    GRANT ALL ON PCKG_TRANSACT TO DEVELOPER; 
    GRANT ALL ON PCKG_VIOLATIONS TO DEVELOPER;
    GRANT ALL ON PCKG_UTILS TO DEVELOPER;

    GRANT ALL ON ANALYST_VIEW TO DEVELOPER;
    GRANT ALL ON SUPPORT_VIEW TO DEVELOPER;
    GRANT ALL ON AUDIT_VIEW TO DEVELOPER;

---------------------------------------
---         TESTER
---------------------------------------
    GRANT CONNECT, CREATE SESSION to TESTER;
    GRANT SELECT, INSERT, UPDATE ON ACTIVITY to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CAR to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CARS_AT_PICKUP to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CUSTOMER_ADDRESS to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CUSTOMERS to TESTER;
    GRANT SELECT, INSERT, UPDATE ON DISCOUNTS to TESTER;
    GRANT SELECT, INSERT, UPDATE ON FEEDBACK to TESTER;
    GRANT SELECT, INSERT, UPDATE ON INSURANCE to TESTER;
    GRANT SELECT, INSERT, UPDATE ON MAINTENANCE to TESTER;
    GRANT SELECT, INSERT, UPDATE ON PAYMENTS to TESTER;
    GRANT SELECT, INSERT, UPDATE ON PICKUP_POINTS to TESTER;
    GRANT SELECT, INSERT, UPDATE ON PURCHASE_INSURANCE to TESTER;
    GRANT SELECT, INSERT, UPDATE ON RIDE_TRANSACTION to TESTER;
    GRANT SELECT, INSERT, UPDATE ON SUPPORT to TESTER;
    GRANT SELECT, INSERT, UPDATE ON VIOLATIONS to TESTER;
    GRANT SELECT, INSERT, UPDATE ON VIOLATIONS_RECORDS to TESTER;
    
    GRANT EXECUTE ON PCKG_CAR TO TESTER;
    GRANT EXECUTE ON PCKG_CUSTOMER TO TESTER;
    GRANT EXECUTE ON PCKG_INSURANCE TO TESTER;
    GRANT EXECUTE ON PCKG_SERVICE TO TESTER;
    GRANT EXECUTE ON PCKG_TRANSACT TO TESTER; 
    GRANT EXECUTE ON PCKG_VIOLATIONS TO TESTER;
    GRANT EXECUTE ON PCKG_UTILS TO TESTER;

    GRANT ALL ON ANALYST_VIEW TO TESTER;
    GRANT ALL ON SUPPORT_VIEW TO TESTER;
    GRANT ALL ON AUDIT_VIEW TO TESTER;

---------------------------------------
---  ANALYST 
---------------------------------------
    GRANT  CONNECT, CREATE SESSION to ANALYST;
    GRANT SELECT ON ANALYST_VIEW TO ANALYST;

---------------------------------------
---         SERVICE
---------------------------------------
    GRANT CONNECT, CREATE SESSION to SERVICE;
    GRANT EXECUTE ON PCKG_CAR TO SERVICE;
    GRANT EXECUTE ON PCKG_CUSTOMER TO SERVICE;
    GRANT EXECUTE ON PCKG_INSURANCE TO SERVICE;
    GRANT EXECUTE ON PCKG_SERVICE TO SERVICE;
    GRANT EXECUTE ON PCKG_TRANSACT TO SERVICE; 
    GRANT EXECUTE ON PCKG_VIOLATIONS TO SERVICE;
    GRANT ALL ON PCKG_UTILS TO SERVICE;
    
    GRANT SELECT ON ANALYST_VIEW TO SERVICE;
    GRANT SELECT ON SUPPORT_VIEW TO SERVICE;
    GRANT SELECT ON AUDIT_VIEW TO SERVICE;
    
---------------------------------------
---  SECURITY
---------------------------------------
    GRANT CONNECT, CREATE SESSION to SECURITY;
    GRANT SELECT ON AUDIT_VIEW TO SECURITY;
    
---------------------------------------

 -- SELECT * FROM role_sys_privs where ROLE IN ('APP_OWNER','DEVELOPER','TESTER','ANALYST','SERVICE','SECURITY');
 -- SELECT * FROM role_tab_privs where ROLE IN ('APP_OWNER','DEVELOPER','TESTER','ANALYST','SERVICE','SECURITY');
----------------------------------------
-- #####################################
----------------------------------------

----------------------------------------
--              USERS
----------------------------------------
    --APP_OWNER
    CREATE USER JARVIS IDENTIFIED BY Blender12345; 
    --DEVELOPER
    CREATE USER HARRY IDENTIFIED BY Blender12345;
    --TESTER
    CREATE USER PETER IDENTIFIED BY Blender12345;
    --ANALYST
    CREATE USER TOM IDENTIFIED BY Blender12345;
    --SERVICE
    CREATE USER ROOT IDENTIFIED BY Blender12345;
    --AUDIT
    CREATE USER JESSY IDENTIFIED BY Blender12345;


  --  select * from dba_users where username in ('HARRY', 'JARVIS', 'PETER', 'TOM', 'ROOT', 'JESSY');

-----------------------------------------
-- ######################################
-----------------------------------------

-----------------------------------------
-- ROLES - USERS
-----------------------------------------

    GRANT APP_OWNER TO JARVIS;
    GRANT DEVELOPER TO HARRY;
    GRANT TESTER TO PETER;
    GRANT ANALYST TO TOM;
    GRANT SERVICE TO ROOT;
    GRANT SECURITY TO JESSY;

-----------------------------------------

    -- SELECT * FROM session_roles;
    
    -- SELECT * FROM user_role_privs;
    -- SELECT * FROM role_sys_privs where ROLE IN ('APP_OWNER','DEVELOPER','TESTER','ANALYST','SERVICE','SECURITY');
    -- SELECT * FROM role_tab_privs where ROLE IN ('APP_OWNER','DEVELOPER','TESTER','ANALYST','SERVICE','SECURITY');
    
    -- select * from ALL_TABLES where OWNER = 'ADMIN';
    -- select * from DBA_ROLE_PRIVS where grantee = 'ADMIN';
    
    -- SELECT * FROM dba_role_privs where GRANTED_ROLE IN ('ADMIN', 'APP_OWNER', 'DEVELOPER', 'TESTER', 'ANALYST', 'SERVICE', 'SECURITY');
